### ISSUE TITLE
TupleOf Modifier Type

### ISSUE THREAD

**Issue by DanielAsher** [typelift/SwiftCheck#106]
Hi,
I am unable to compose tuples with the `ArrayOf` modifier so:

`forAll { (ids: ArrayOf<(ArbitraryID, ArbitraryID)>) ...` 

which causes compiler error 

`Type (ArbitraryID, ArbitraryID) does not conform to protocol Arbitrary`

Should I attempt a `TupleOf` modifier type or is there a smarter way to go about this?

cheers,

Daniel

**Comment by CodaFi** [comment]
This is what I was trying to avoid with the overloads of `forAll` because Tuples are still an opaque feature of the language and, still way too hard to work with generically.  You can accomplish this with 2 arrays and `zip` for now.  The hope is Swift gives us Scala-style tuple extensions so I can make `forAll` polyvariadic over tuples of size N and we won't have to ship something like `TupleOf`

**Comment by DanielAsher** [comment]
thanks @CodaFi

is there an example of using the curried `forAll` ? I couldn't get it working without tuples as per #107

**Comment by CodaFi** [comment]
It's overload resolution that's biting you.  Gimme a second, I've got a workaround on my end

**Comment by CodaFi** [comment]
Fixed by the merge of #108.

**Comment by DanielAsher** [comment]
I've removed `TupleOf` from my fork. hope to leave it on the plate before scraping into the garbage :)
