### ISSUE TITLE
Consolidate Swift 2.3 & Swift 3.0 support

### ISSUE THREAD

**Issue by bgerstle** [typelift/SwiftCheck#167]
I noticed there are two separate 2.3 & 3.0 branches. Is it too cumbersome to use the Swift version preprocessor facilities to keep 2.3 & 3.0 support in the same branch?  For example:

``` swift
#if swift(>=2.3) 
    return .none
#else
    return .None
#endif
```

Seems untenable to maintain multiple branches for each new Swift version.  Also, keeping it in the same repo allows people who are gradually adopting 3.0 to also use SwiftCheck's 3.0 API when possible.  Thoughts?

**Comment by griotspeak** [comment]
I was/am going to make an issue for making an strategy for support going forward. The plist involvement complicates the preprocessor strategy a little bit.

**Comment by griotspeak** [comment]
Thinking about this more, I don't think that a preprocessor approach would be desirable. The changes to the standard library, for one, mean that we would need to have significant amounts of code in these blocks.

**Comment by bgerstle** [comment]
You're probably right, then is the code effectively frozen for Swift 2.2 &
2.3—barring any major hotfixes for 2.3? Doesn't make sense to try to
maintain both in parallel.

**Comment by griotspeak** [comment]
I think that the plan should be two releases once Xcode 8.0 and Swift 3.0/2.3 are official.

One with 2.3 support

**Comment by griotspeak** [comment]
I think that the correct path forward is to support 2.3 until the official release of 3.0.

The codebase works with 2.2 without issue when updated to 2.3. This means that we can officially support 2.3 right now without causing any undue stress. Once 3.0 is official, we 'move on' from 2.3 barring hot fixes.

**Comment by CodaFi** [comment]
The strategy is the same one Typelift has always had.  We are going to support Swift 3, not Swift 2.3. This framework will have one more compatibility release for 2.3 if it hasn't already then our support for legacy Swift will end entirely and we will continue work on the 3.0 branch until it gets merged for master.  Because we haven't found any showstopping bugs during the beta period, I don't see a reason to maintain an entire 2.3 branch or introduce a bunch of ifdefs to try and scavenge legacy support back.
