### ISSUE TITLE
Double to Int conversion fails with error

### ISSUE THREAD

**Issue by moogle19** [typelift/SwiftCheck#205]
Version
========

0e2d31cbf718cc31bb2f80a65760439ecc3ee7fc

Environment
===========

macOS 10.12.1, XCode 8.2.1, Swift 3

Description
============

When calling `Int64.randomInRange` (and `Int` on 64 bit) with a range of `(Int64.max, Int64.max)` I get an error. The conversion `Int64(Double(UInt64.max))` in [Random.swift](https://github.com/typelift/SwiftCheck/blob/master/Sources/Random.swift#L212) fails, because `Double(Int64.max) > Int64.max`

(Same for `UInt64` (and `UInt` on 64 bit))

Steps To Reproduce
===================

Just run `Int64.randomInRange((Int64.max, Int64.max), gen: StdGen(1))`

Expected Result
================

Should return `Int64.max`

Actual Result
==============

fatal error: Double value cannot be converted to Int64 because the result would be greater than Int64.max

Additional information
======================

**Comment by CodaFi** [comment]
[I knew this could come back to bite me](https://github.com/typelift/SwiftCheck/commit/44ec84b341c3a8697daf961f37c0614398bb5185) at some point.

I'm at a loss here.  There is a range of 512 unconvertible-yet-representable `Int64` values subject to this crash because of the preconditions in the initializer getting tripped here.

**Comment by CodaFi** [comment]
Resolved by the merge of #208.  Please point your package manager at master until I put out a new point release.
