### ISSUE TITLE
Custom Generators and Modifier types.

### ISSUE THREAD

**Issue by cnicolai** [typelift/SwiftCheck#223]
Hi there! Thank you for your work at typelift! 
I ran into the following situation and I am not sure whether it is a bug or me doing something weird. Any comments are very appreciated.

Version
========

4264442ff76c66600d7dc0e6241f0eb247d91ba2

Environment
===========

Mac

Description
============

When passing a custom `Gen` to `forAll` and then using a Modifier-Type, the test won't compile. 

```swift
let evenInt: Gen<Int> = Int.arbitrary.suchThat { $0 % 2 == 0 }

property("Well defined property name") <- forAll(evenInt) { (ns: ArrayOf<Int>) in
    return ns.getArray.count >= 0
}
```

Expected Result
================

Compilation.

Actual Result
==============

Compiler error:
Cannot convert value of type `Bool` to closure result type `Testable`.

**Comment by broomburgo** [comment]
Hi, your `evenInt` is a `Gen<Int>`, so it generates values of type `Int`. But in the closure passed to `forAll` you are specifying an input of type `ArrayOf<Int>`.

So your `evenInt` generator should really be a `Gen<ArrayOf<Int>>` for the code to compile.

You can define one like the following:

```swift
let evenInts = evenInt.proliferate.map(ArrayOf.init)
```

Now:

- `.proliferate` turns any generator of `A` into a generator of `[A]`;
- `.map(ArrayOf.init)` will turn the `Gen<[Int]>` into a `Gen<ArrayOf<Int>>` (this is needed because you still need to pass a `Gen<Arbitrary>` to `forAll` and `[Int]` is not `Arbitrary`, while `ArrayOf<Int>` is.

Finally, pass `evenInts` to `forAll`.

Here's the whole code:

```swift
let evenInt = Int.arbitrary.suchThat { $0 % 2 == 0 }
let evenInts = evenInt.proliferate.map(ArrayOf.init)
		
property("Well defined property name") <- forAll(evenInts) { (ns: ArrayOf<Int>) in
	return ns.getArray.count >= 0
}
```

Hope this helps.

**Comment by cnicolai** [comment]
Hi, thank you very much for your reply, it does help a lot!
I actually tried to proliferate, but forgot to map with `ArrayOf.init`.
