### ISSUE TITLE
Make Gen.frequency Less Terrifying

### ISSUE THREAD

**Issue by CodaFi** [typelift/SwiftCheck#25]
We need a version that maps pure across the second part of each tuple of normal values rather than generators.

**Comment by robrix** [comment]
I took a quick stab at this and ran into some interesting trouble: since `A` in `Gen<A>` is unconstrained, `Gen.frequency([ (1, Gen.pure(0)) ])` is ambiguous between `Gen<Int>` and `Gen<Gen<Int>>`.

What do you think about _replacing_ the current `Gen.frequency` with the first-order version you describe and then using `join` to recover the current functionality?

**Comment by CodaFi** [comment]
Just write a new one rather than overload is what I was thinking (Gen.weighted?).

**Comment by robrix** [comment]
Fair enough!
