### ISSUE TITLE
Practical guide to using SwiftCheck with business logic?

### ISSUE THREAD

**Issue by swizzlr** [typelift/SwiftCheck#77]
Forgive the obtuse title – I'm looking for resources that might help me with using property-testing on larger parts of my app than "check that my sorting algorithm works" e.g.

- verifying that adding and deleting objects from a database behaves correctly
- verifying that user input to a view model is correctly handled

etc.

In short, I'm trying to get a feel for "Real World SwiftCheck" (or QuickCheck, for that matter). I'm also interested in how I can apply SwiftCheck to less functionally oriented code to achieve useful results.

For me, I'd consider this issue closed when I can see any or all of:
- examples of SwiftCheck being used in an application
- blog posts/tutorials
- book recommendations for the analogous QuickCheck style frameworks in other languages

Thanks!

**Comment by CodaFi** [comment]
It's good you opened this issue, then, because I can't give you many recommendations.  This is a young framework with a volatile API using Haskell-isms; all three being on their own infertile ground for "practical examples".  For now, I can only point you to the rest of TypeLift's frameworks and their tests and a few other frameworks I personally know of that have used SwiftCheck to great effect:

TypeLift:

[Using SwiftCheck to verify algebraic laws](https://github.com/typelift/Swiftz/blob/swift-develop/SwiftzTests/ListSpec.swift).
[Using SwiftCheck to model the states of concurrent types](https://github.com/typelift/Concurrent/blob/swift-develop/ConcurrentTests/ChanSpec.swift)
[Using SwiftCheck with higher-order types](https://github.com/typelift/Swiftx/blob/swift-development/SwiftxTests/EitherSpec.swift#L52)
[Using SwiftCheck for fun](https://github.com/typelift/SwiftCheck/blob/swift-develop/SwiftCheckTests/PropertySpec.swift#L17) and [profit](https://github.com/typelift/SwiftCheck/blob/swift-develop/SwiftCheckTests/BooleanIdentitySpec.swift)

griotspeak/Rational

[Using SwiftCheck with custom types](https://github.com/griotspeak/Rational/blob/master/RationalTests/RationalTests.swift)

TabletopAssistant/DiceKit

[Using SwiftCheck in a robust testing suite](https://github.com/TabletopAssistant/DiceKit/tree/f51895369f39bc21f3dd39235838e512f47596be/DiceKitTests)

You seem to already have an idea that you'll have more luck looking in other places for this stuff.  Unfortunately, SwiftCheck doesn't implement nearly as much of the fancy features QuickCheck does [type system limitations, you understand], but what we do get is compatible with these posts:

[Practical testing in Haskell](http://jaspervdj.be/posts/2015-03-13-practical-testing-in-haskell.html)
[QuickCheck and WebDriver](https://www.fpcomplete.com/user/christianpbrink/quickcheck-and-webdriver)
[Arbitrary Fun: Generating User Profiles with QuickCheck](http://chromaticleaves.com/posts/generate-user-data-quickcheck.html)

and many more.  In general, unless you're specifically using the Monadic extensions to QuickCheck, most any blog post or library suite you find should translate.  That means you can take a look at test suites for pretty much [any Haskell library](https://github.com/search?q=import+Test+QuickCheck+language%3AHaskell&type=Code&utf8=✓) and get a quick feel for how to do most things.

I'm sorry I can't offer much in the way of a demo application or good advice yet.  Truth is even I'm still trying to flesh out and separate this framework from its Haskell roots.  The more I do that the better my advice will get, but for now this is all I've got.

**Comment by CodaFi** [comment]
But I do want to address one particular point of your post

> how I can apply SwiftCheck to less functionally oriented code

While SwiftCheck has not been used to test that style of program, they are not fundamentally incompatible.  But you must be careful when you deviate from the idea that a program is a function of its state.  SwiftCheck is, above all, about consistency between testing runs.  You will have a *terrible* time trying to use SwiftCheck to check a globally mutable environment or a use a suite that depends on a number of un Gen-able factors.  This means UI and interaction should be generated statically, which is possible in theory.  I have been meaning to look into integration with the new UI automation and testing facilities in Xcode, which I suspect is what you're after.

**Comment by swizzlr** [comment]
Wow, thank you so much! That's super useful, and I feel like I have a good starting point. I'll check back if I have anything to report.

**Comment by CodaFi** [comment]
Absolutely.  Feel free to open more issues like this.  I want this framework to make its way into the iOS and OS X testing world.  If you can make it over the learning curve, it forces you to really take a step back and reason about your code in more profound ways than traditional forms of TDD or BDD.
